services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kanastra-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 20
    depends_on:
      - zookeeper
    networks:
      - kanastra-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanastra-api
    ports:
      - "8084:8084"
    environment:
      BROKER_ADDRESS: "kafka:9092"
      TOPIC: "debt_topic"
      GROUP_ID: "billing_group"
      HTTP_PORT: "8084"
    depends_on:
      - kafka
    networks:
      - kanastra-network

networks:
  kanastra-network:
    driver: bridge